### ISSUE TITLE
Internal error: unknown parameter stereo.left.image_rect.enable_pub_plugins

### ISSUE THREAD

**Issue by flixr** [roboception/rc_genicam_driver_ros2#10]
Created separate issue for this from #9

Seems there is a regression in humble and iron leading to errors at startup:
```
[ERROR] [1717697123.623517722] [my_visard.genicam_driver]: parameter 'stereo.left.image_rect.enable_pub_plugins' could not be set: Internal error: unknown parameter stereo.left.image_rect.enable_pub_plugins
[FATAL] [1717697126.624600300] [my_visard.genicam_driver]: parameter 'camera_exp_auto_average_max' has invalid type: cannot undeclare a statically typed parameter
```

**Comment by flixr** [comment]
@ralphieraccoon this is caused by the latest backport of the allowlist to image_transport 1.3.9 which internally adds the parameter `enable_pub_plugins` and we didn't expect/handle other parameters to be added.
Will be fixed shortly.

**Comment by flixr** [comment]
Should be fixed with v0.3.1.
Will also bloom release it, but could take a while until its built and synced from the ROS buildfarm...

**Comment by ralphieraccoon** [comment]
Thanks! Will try it on Monday.

**Comment by ralphieraccoon** [comment]
Tested it this morning, seems to work fine.
