### ISSUE TITLE
ros2 param set genicam_driver fails with symbol lookup error in ros2-iron

### ISSUE THREAD

**Issue by DanBmh** [roboception/rc_genicam_driver_ros2#5]
Using the apt installation of `ros-iron-rc-genicam-driver` raised following error on setting a parameter:

```
subprocess.CalledProcessError: Command '['bash', '-c', 'ros2 param set /cam_klein_bunt/genicam_driver camera_exp_control "Auto"']' returned non-zero exit status 1.
cam_klein_bunt_1          | /opt/ros/iron/lib/rc_genicam_driver/rc_genicam_driver: symbol lookup error: /opt/ros/iron/lib/librc_genicam_driver_core.so: undefined symbol: _ZN15image_transport16create_publisherEPN6rclcpp4NodeERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE17rmw_qos_profile_sNS0_29PublisherOptionsWithAllocatorISaIvEEE
cam_klein_bunt_1          | [ros2run]: Process exited with failure 127
```

I could solve it by installing the repository from source.

**Comment by flixr** [comment]
Which exact version did you use from the repo? And which version did you build from source?
This is on Ubuntu jammy I presume?

**Comment by DanBmh** [comment]
The apt version from today (not sure about the number), the source version from today's master branch. 
Yes, ubuntu 22.04

**Comment by flixr** [comment]
Hm, then the version should be the same. Maybe a buildfarm issue...
If you built it in a prebuilt ROS docker image, did you do a `apt-get update && apt-get upgrade` before installing ros-iron-rc-genicam-driver?
If not, please try that, otherwise you might have package mismatches...

**Comment by DanBmh** [comment]
i've used an ubuntu 22 based image and installed ros2 via apt (today as well) but `apt-get upgrade` which was run earlier in the build was cached (a few weeks old). I always used `apt-get update` in each step.

**Comment by flixr** [comment]
The last rc_genicam_driver build is 27 days old, seems there were a couple of automatic rebuilds on the buildfarm:
https://build.ros2.org/job/Ibin_uJ64__rc_genicam_driver__ubuntu_jammy_amd64__binary/
