### ISSUE TITLE
Package 'rc_genicam_driver' not found

### ISSUE THREAD

**Issue by NiklasEiler** [roboception/rc_genicam_driver_ros2#7]
Hello, i can run all rc_genicam_api fuction and can also detect thee device, but when i run the ros2 test line i get an error(complet terminal output below). Do you know what is wrong and how i can fix it ?

niklas@niklas-desktop:~$ gc_config -l
Available GigE Vision devices:
  eth0:02940786 (rc_visard 160m, devicemodul00_14_2d_2c_df_72)
niklas@niklas-desktop:~$ gc_info -l
Transport Layer /usr/lib/aarch64-linux-gnu/rc_genicam_api/libbgapi2_gige.cti_2.9.22968.22969
Vendor:         Baumer
Model:          bgapi2_gige
Vendor version: 2.9.22968.22969
TL type:        GEV
Name:           libbgapi2_gige.cti
Pathname:       /usr/lib/aarch64-linux-gnu/rc_genicam_api/libbgapi2_gige.cti
Display name:   Baumer GEV TL
GenTL version   1.5

    Interface     eth0
    Display name: eth0
    TL type:      GEV

        Device             devicemodul00_14_2d_2c_df_72
        Vendor:            Roboception GmbH
        Model:             rc_visard 160m
        TL type:           GEV
        Display name:      rc_visard 160m
        User defined name: 
        Access status:     ReadWrite
        Serial number:     02940786
        Version:           
        TS Frequency:      0

    Interface     wlan0
    Display name: wlan0
    TL type:      GEV

Transport Layer /usr/lib/aarch64-linux-gnu/rc_genicam_api/libbgapi2_usb.cti_2.9.22669.22969
Vendor:         Baumer
Model:          bgapi2_usb
Vendor version: 2.9.22669.22969
TL type:        U3V
Name:           libbgapi2_usb.cti
Pathname:       /usr/lib/aarch64-linux-gnu/rc_genicam_api/libbgapi2_usb.cti
Display name:   Baumer U3V TL
GenTL version   1.5

    Interface     USB
    Display name: USB HOST
    TL type:      U3V

niklas@niklas-desktop:~$ ros2 run rc_genicam_driver rc_genicam_driver --ros-args -p "device:=:02940786"
Package 'rc_genicam_driver' not found

**Comment by heikohimu** [comment]
ROS 2 is complaining that the package 'rc_genicam_driver', i.e. the ROS2 driver node is not found. It has nothing to do with the rc_genicam_api package that is used by the driver. Did you install (or build) the rc_genicam_driver package?

**Comment by NiklasEiler** [comment]
How do I install  'rc_genicam_driver' for Ros2? I only found the one for ros and that one is to old.

**Comment by NiklasEiler** [comment]
[ERROR] [1700491509.691750597] [genicam_driver]: Device version must be 20.04 or higher: 1.8.4
That is the Error
