### ISSUE TITLE
Connect to new stereo camera failed

### ISSUE THREAD

**Issue by NiklasEiler** [roboception/rc_genicam_driver_ros2#9]
Hello,
I worked with one stereo camera viscard 160 and I can connect without any problem, but I tried to connect to a stereo camera of the same model today and ran into these error messages after running the ros2 start command. What should I change to get rid of the error?
Best regrets Niklas Eilers 
[ERROR] [1702468796.274008351] [genicam_driver]: parameter 'depth_maxdeptherr' could not be set: Parameter {depth_maxdeptherr} doesn't comply with floating point range. 
[INFO] [1702468799.274645626] [genicam_driver]: Cleanup 
[FATAL] [1702468799.275120101] [genicam_driver]: parameter 'camera_exp_auto_average_max' has invalid type: cannot undeclare an statically typed parameter 
[INFO] [1702468799.275475837] [genicam_driver]: Processing thread stopped

**Comment by ralphieraccoon** [comment]
> I solved it

How did you solve this? I'm having the same problem.

**Comment by NiklasEiler** [comment]
After an update of the camera software, the program connected to the camera without any problem. But sometimes, the error with the distance option occurs because the camera doesn’t find enough features to calculate the point cloud.

**Comment by ralphieraccoon** [comment]
> After an update of the camera software, the program connected to the camera without any problem. But sometimes, the error with the distance option occurs because the camera doesn’t find enough features to calculate the point cloud.

That's strange, I just did a firmware update. I'll try running the update again, maybe it didn't do it properly.

**Comment by flixr** [comment]
What firmware version do you have? You can see that in the WebGUI under System.

**Comment by ralphieraccoon** [comment]
> What firmware version do you have? You can see that in the WebGUI under System.

**24.04.2**

**Comment by flixr** [comment]
Exactly the same one?

**Comment by ralphieraccoon** [comment]
> Exactly the same one?

Yes, see below:

```
[INFO] [1717436849.689009269] [my_visard.genicam_driver]: Initializing
[INFO] [1717436849.689166726] [my_visard.genicam_driver]: Processing thread started
[INFO] [1717436849.689209591] [my_visard.genicam_driver]: Configuring
[INFO] [1717436852.828961849] [my_visard.genicam_driver]: Connecting to sensor 'eno1:02940632' alias rc_visard 65c
[ERROR] [1717436854.388562353] [my_visard.genicam_driver]: parameter 'depth_maxdeptherr' could not be set: Parameter {depth_maxdeptherr} doesn't comply with floating point range.
[INFO] [1717436857.389145726] [my_visard.genicam_driver]: Cleanup
[FATAL] [1717436857.389431542] [my_visard.genicam_driver]: parameter 'camera_exp_auto_average_max' has invalid type: cannot undeclare a statically typed parameter
[INFO] [1717436857.389627707] [my_visard.genicam_driver]: Processing thread stopped
```

**Comment by flixr** [comment]
Could you please provide the OS/version you are using, the version of rc_genicam_driver (compiled from source or from ROS buildfarm?) and post the current parameters of the rc_visard (WebGUI -> System -> download settings).

**Comment by ralphieraccoon** [comment]
> Could you please provide the OS/version you are using, the version of rc_genicam_driver (compiled from source or from ROS buildfarm?) and post the current parameters of the rc_visard (WebGUI -> System -> download settings).

I'm running **ROS Iron** on **Ubuntu 22.04.4**. `rc_genicam_driver` is from the [buildfarm](https://index.ros.org/p/rc_genicam_driver/#iron). Settings are attached:

[rc_visard-02940632-settings_2024-06-03T18 04 59.243Z.json](https://github.com/user-attachments/files/15537896/rc_visard-02940632-settings_2024-06-03T18.04.59.243Z.json)

**Comment by NiklasEiler** [comment]
I can check this tomorrow

**Comment by NiklasEiler** [comment]
I run ros2 humble on Ubuntu 22.04 lts

**Comment by flixr** [comment]
Looks like something changed with humble regarding the parameters, it still works as expected in foxy.
We'll need to debug this a bit more and fix it.

**Comment by flixr** [comment]
The floating point range error should be fixed with https://github.com/roboception/rc_genicam_driver_ros2/commit/9f5d24e604a087609d531244be43e97530aa0b73
